name: Run make and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - uses: actions/upload-artifact@v2.3.1
      with:
        name: make artifact
        path: circleMonte

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2.1.0
      with:
        name: make artifact
        path: ./
    - name: run test
      run: ./testMonte.sh
